//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBFC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboProductMap
    {
        public Nullable<bool> IsActive { get; set; }
        public int ComboId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Product Product { get; set; }
    }
}
