//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBFC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCategoryMap
    {
        public int Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ShopCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ShopCategory ShopCategory { get; set; }
    }
}
